// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
  show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
  // Only support Android and iOS
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8', // Replace with actual API key
    appId: '1:283937135425:android:1b76e5af09b25394c5dfc0',
    messagingSenderId: '283937135425',
    projectId: 'maa-yegue',
    storageBucket: 'maa-yegue.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8', // Replace with actual API key
    appId: '1:283937135425:ios:1b76e5af09b25394c5dfc0', // Replace with actual iOS app ID
    messagingSenderId: '283937135425',
    projectId: 'maa-yegue',
    storageBucket: 'maa-yegue.appspot.com',
    iosBundleId: 'com.mayegue.app', // Replace with actual bundle ID
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8', // Replace with actual API key
    appId: '1:283937135425:macos:1b76e5af09b25394c5dfc0', // Replace with actual macOS app ID
    messagingSenderId: '283937135425',
    projectId: 'maa-yegue',
    storageBucket: 'maa-yegue.appspot.com',
    iosBundleId: 'com.mayegue.app', // Replace with actual bundle ID
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8', // Replace with actual API key
    appId: '1:283937135425:web:95b5de88274a802cc5dfc0',
    messagingSenderId: '283937135425',
    projectId: 'maa-yegue',
    storageBucket: 'maa-yegue.appspot.com',
    authDomain: 'maa-yegue.firebaseapp.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8', // Replace with actual API key
    appId: '1:283937135425:windows:1b76e5af09b25394c5dfc0', // Replace with actual Windows app ID
    messagingSenderId: '283937135425',
    projectId: 'maa-yegue',
    storageBucket: 'maa-yegue.appspot.com',
  );
}
